spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: producto-service
              uri: lb://productoService
              predicates:
                - Path=/api/productos/**
              filters:
                - StripPrefix=0
            - id: inventarioService
              uri: lb://inventarioService
              predicates:
                - Path=/api/inventario/**
              filters:
                - StripPrefix=0

            - id: producto-service-swagger
              uri: lb://productoService
              predicates:
                - Path=/swagger/productos/v3/api-docs
              filters:
                - RewritePath=/swagger/productos/v3/api-docs, /v3/api-docs

            - id: producto-service-swagger-ui
              uri: lb://productoService
              predicates:
                - Path=/swagger/productos/swagger-ui/**
              filters:
                - RewritePath=/swagger/productos/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

            - id: inventario-service-swagger
              uri: lb://inventarioService
              predicates:
                - Path=/swagger/inventario/v3/api-docs
              filters:
                - RewritePath=/swagger/inventario/v3/api-docs, /v3/api-docs

            - id: inventario-service-swagger-ui
              uri: lb://inventarioService
              predicates:
                - Path=/swagger/inventario/swagger-ui/**
              filters:
                - RewritePath=/swagger/inventario/swagger-ui/(?<segment>.*), /swagger-ui/${segment}